# -*- coding: utf-8 -*-
"""CartPole-v1 DQL Agent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15Ld64j3dbK2yF3fS4WxdW_urTdtk-66F
"""

!pip install gymnasium torch matplotlib

import random
import numpy as np
import torch
import torch.nn as nn
import torch.optim as optim
import gymnasium as gym
from collections import deque
import matplotlib.pyplot as plt

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

env = gym.make("CartPole-v1")

state_dim = env.observation_space.shape[0]
action_dim = env.action_space.n

class DQN(nn.Module):
    def __init__(self):
        super(DQN, self).__init__()
        self.net = nn.Sequential(
            nn.Linear(state_dim, 128),
            nn.ReLU(),
            nn.Linear(128, 128),
            nn.ReLU(),
            nn.Linear(128, action_dim)
        )

    def forward(self, x):
        return self.net(x)

model = DQN().to(device)
target_model = DQN().to(device)
target_model.load_state_dict(model.state_dict())

optimizer = optim.Adam(model.parameters(), lr=5e-4)
loss_fn = nn.MSELoss()

memory = deque(maxlen=10000)

gamma = 0.99
batch_size = 64
epsilon = 1.0
epsilon_min = 0.01
epsilon_decay = 0.997
target_update = 20

rewards_list = []
episode_lengths = []
losses = []
epsilons = []

def select_action(state):
    if random.random() < epsilon:
        return env.action_space.sample()
    state = torch.FloatTensor(state).to(device)
    with torch.no_grad():
        return torch.argmax(model(state)).item()

def store_transition(s, a, r, s_next, done):
    memory.append((s, a, r, s_next, done))

def train_step():
    if len(memory) < batch_size:
        return None

    batch = random.sample(memory, batch_size)
    states, actions, rewards, next_states, dones = zip(*batch)

    states = torch.FloatTensor(states).to(device)
    actions = torch.LongTensor(actions).unsqueeze(1).to(device)
    rewards = torch.FloatTensor(rewards).to(device)
    next_states = torch.FloatTensor(next_states).to(device)
    dones = torch.FloatTensor(dones).to(device)

    q_values = model(states).gather(1, actions).squeeze()

    with torch.no_grad():
        next_q = target_model(next_states).max(1)[0]
        target_q = rewards + gamma * next_q * (1 - dones)

    loss = loss_fn(q_values, target_q)

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    return loss.item()

episodes = 2000

for episode in range(episodes):
    state, _ = env.reset()
    total_reward = 0
    step_count = 0
    episode_loss = []

    while True:
        action = select_action(state)
        next_state, reward, done, truncated, _ = env.step(action)

        store_transition(state, action, reward, next_state, done)

        loss = train_step()
        if loss is not None:
            episode_loss.append(loss)

        state = next_state
        total_reward += reward
        step_count += 1

        if done or truncated:
            break

    rewards_list.append(total_reward)
    episode_lengths.append(step_count)
    epsilons.append(epsilon)

    if len(episode_loss) > 0:
        losses.append(np.mean(episode_loss))
    else:
        losses.append(0)

    epsilon = max(epsilon_min, epsilon * epsilon_decay)

    if episode % target_update == 0:
        target_model.load_state_dict(model.state_dict())

    print(f"Episode {episode}, Reward: {total_reward}, Epsilon: {epsilon:.3f}")

env.close()

import numpy as np
import matplotlib.pyplot as plt

# Convert to numpy
rewards = np.array(rewards_list)
lengths = np.array(episode_lengths)
loss_arr = np.array(losses)
eps_arr = np.array(epsilons)

# ---------- FUNCTION TO COMPUTE METRICS ----------
def compute_metrics(rewards, lengths, loss_arr, eps_arr, label="ALL EPISODES"):
    print(f"\n========== {label} ==========\n")

    print("1. TD Error (Mean):", loss_arr.mean())
    print("2. Average Reward:", rewards.mean())
    print("3. Max Reward:", rewards.max())
    print("4. Min Reward:", rewards.min())

    print("\n5. Reward Variance:", rewards.var())
    print("6. Reward Std Dev:", rewards.std())

    print("\n7. Average Episode Length:", lengths.mean())
    print("8. Max Episode Length:", lengths.max())

    success_threshold = 195
    success_rate = np.sum(rewards >= success_threshold) / len(rewards)
    print("\n9. Success Rate:", success_rate)

    print("\n10. Average Loss:", loss_arr.mean())
    print("11. Final Loss:", loss_arr[-1])

    print("\n12. Final Epsilon:", eps_arr[-1])

    # Convergence Episode
    window = 20
    convergence_episode = -1
    for i in range(len(rewards) - window):
        if rewards[i:i+window].mean() >= success_threshold:
            convergence_episode = i
            break

    print("\n13. Convergence Episode:", convergence_episode)

    # Regret
    optimal_reward = 500
    regret = np.sum(optimal_reward - rewards)
    print("\n14. Total Regret:", regret)


# ---------- COMPUTE METRICS ----------
compute_metrics(rewards, lengths, loss_arr, eps_arr, "ALL 2000 EPISODES")
compute_metrics(rewards[-200:], lengths[-200:], loss_arr[-200:], eps_arr[-200:], "LAST 200 EPISODES")


# ---------- MOVING AVERAGE FUNCTION ----------
def moving_avg(data, window=50):
    return np.convolve(data, np.ones(window)/window, mode='valid')


# =========================
# 📊 GRAPHS (ALL EPISODES)
# =========================

# Episode Reward
plt.figure()
plt.plot(rewards)
plt.title("Episode Reward (All Episodes)")
plt.xlabel("Episode")
plt.ylabel("Reward")
plt.show()

# Moving Average Reward
plt.figure()
plt.plot(moving_avg(rewards))
plt.title("Moving Average Reward (All Episodes)")
plt.xlabel("Episode")
plt.ylabel("Reward")
plt.show()

# Loss Curve
plt.figure()
plt.plot(loss_arr)
plt.title("Loss Curve (All Episodes)")
plt.xlabel("Episode")
plt.ylabel("Loss")
plt.show()

# Episode Length
plt.figure()
plt.plot(lengths)
plt.title("Episode Length (All Episodes)")
plt.xlabel("Episode")
plt.ylabel("Steps")
plt.show()

# Epsilon Decay
plt.figure()
plt.plot(eps_arr)
plt.title("Exploration (Epsilon Decay)")
plt.xlabel("Episode")
plt.ylabel("Epsilon")
plt.show()


# =========================
# 📊 GRAPHS (LAST 200 EPISODES)
# =========================

last_rewards = rewards[-200:]
last_lengths = lengths[-200:]
last_losses = loss_arr[-200:]
last_eps = eps_arr[-200:]

# Episode Reward
plt.figure()
plt.plot(last_rewards)
plt.title("Episode Reward (Last 200 Episodes)")
plt.xlabel("Episode")
plt.ylabel("Reward")
plt.show()

# Moving Average Reward
plt.figure()
plt.plot(moving_avg(last_rewards, window=20))
plt.title("Moving Average Reward (Last 200 Episodes)")
plt.xlabel("Episode")
plt.ylabel("Reward")
plt.show()

# Loss Curve
plt.figure()
plt.plot(last_losses)
plt.title("Loss Curve (Last 200 Episodes)")
plt.xlabel("Episode")
plt.ylabel("Loss")
plt.show()

# Episode Length
plt.figure()
plt.plot(last_lengths)
plt.title("Episode Length (Last 200 Episodes)")
plt.xlabel("Episode")
plt.ylabel("Steps")
plt.show()

# Epsilon Decay
plt.figure()
plt.plot(last_eps)
plt.title("Epsilon (Last 200 Episodes)")
plt.xlabel("Episode")
plt.ylabel("Epsilon")
plt.show()

from gymnasium.wrappers import RecordVideo
import torch
import os

# Ensure evaluation is deterministic
epsilon = 0.0
model.eval()

# Clear old videos (optional but recommended)
if os.path.exists("./video"):
    import shutil
    shutil.rmtree("./video")

env = RecordVideo(
    gym.make("CartPole-v1", render_mode="rgb_array"),
    video_folder="./video",
    name_prefix="dqn-eval"
)

state, _ = env.reset()
done = False
total_reward = 0

while not done:
    state_tensor = torch.FloatTensor(state).to(device)

    with torch.no_grad():
        q_values = model(state_tensor).cpu().detach().numpy()

# Add tiny noise to break ties
        action = np.argmax(q_values + np.random.randn(*q_values.shape) * 0.01)

    state, reward, done, truncated, _ = env.step(action)
    total_reward += reward

    if truncated:
        break

env.close()

print("✅ Evaluation Reward (DQN):", total_reward)

from IPython.display import HTML
from base64 import b64encode

video_path = "./video"
video_file = sorted(os.listdir(video_path))[-1]

mp4 = open(f"{video_path}/{video_file}", 'rb').read()
data_url = "data:video/mp4;base64," + b64encode(mp4).decode()

HTML(f"""
<video width=500 controls>
      <source src="{data_url}" type="video/mp4">
</video>
""")

torch.save(model.state_dict(), "dqn_cartpole.pth")

model.load_state_dict(torch.load("dqn_cartpole.pth"))
model.eval()

torch.save(model, "dqn_cartpole_full.pth")

import pickle

with open("dqn_cartpole.pkl", "wb") as f:
    pickle.dump(model.state_dict(), f)

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

keras_model = keras.Sequential([
    layers.Dense(128, activation='relu', input_shape=(4,)),
    layers.Dense(128, activation='relu'),
    layers.Dense(2)
])

pt_weights = model.state_dict()

keras_model.layers[0].set_weights([
    pt_weights['net.0.weight'].cpu().numpy().T,
    pt_weights['net.0.bias'].cpu().numpy()
])

keras_model.layers[1].set_weights([
    pt_weights['net.2.weight'].cpu().numpy().T,
    pt_weights['net.2.bias'].cpu().numpy()
])

keras_model.layers[2].set_weights([
    pt_weights['net.4.weight'].cpu().numpy().T,
    pt_weights['net.4.bias'].cpu().numpy()
])

keras_model.save("dqn_cartpole.keras")

keras_model.save("dqn_cartpole.h5")

!pip install onnx onnxscript

dummy_input = torch.randn(1, 4).to(device)

torch.onnx.export(
    model,
    dummy_input,
    "dqn_cartpole.onnx",
    input_names=["state"],
    output_names=["q_values"],
    opset_version=11
)

torch.onnx.export(
    model,
    dummy_input,
    "dqn_cartpole.onnx",
    input_names=["state"],
    output_names=["q_values"],
    opset_version=11,
    dynamic_axes={
        "state": {0: "batch_size"},
        "q_values": {0: "batch_size"}
    }
)

import json
import numpy as np

# Save hyperparameters
config = {
    "state_dim": 4,
    "action_dim": 2,
    "gamma": gamma,
    "epsilon_min": epsilon_min,
    "epsilon_decay": epsilon_decay,
    "learning_rate": 1e-3
}

with open("config.json", "w") as f:
    json.dump(config, f)

# Save training metrics
np.save("rewards.npy", rewards_list)
np.save("losses.npy", losses)
np.save("episode_lengths.npy", episode_lengths)
np.save("epsilons.npy", epsilons)

model_card = """
# DQN CartPole Agent

This model is a Deep Q-Network trained on CartPole-v1.

## Performance
- Average Reward: 500
- Success Rate: 100%

## Framework
- PyTorch

## Usage
Input: State (4D vector)
Output: Q-values for actions

## Author
Your Name
"""

with open("README.md", "w") as f:
    f.write(model_card)